name: gcloud deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Write .env file
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_FLASK_ENV: "Production"
        envkey_FLASK_DEBUG: "False"
        envkey_FLASK_TESTING: "False"
        envkey_FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
        envkey_MONGO_URI: ${{ secrets.MONGO_URI }}
        envkey_LOGGING_LEVEL: 20
        envkey_FOOTBALL_DATA_KEY: ${{ secrets.FOOTBALL_DATA_KEY }}
        file_name: .env

    - name: Initialize Google Cloud SDK
      uses: zxyle/publish-gae-action@master
      with:
        service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.PROJECT_ID }}

    - name: Publish app to Google App Engine
      run: |
        gcloud auth activate-service-account ${{ secrets.SERVICE_ACCOUNT_EMAIL }} --key-file=client-secret.json
        gcloud config set project ${{ secrets.PROJECT_ID }}
        gcloud -q app deploy app.yaml --promote
