name: gcloud deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Write .env file
      uses: DamianReeves/write-file-action@master
      with:
        path: ${{ env.home }}/.env
        contents: |
          echo "FLASK_ENV = Production"
          echo "FLASK_DEBUG = False"
          echo "FLASK_TESTING = False"
          echo "FLASK_SECRET_KEY = " + {{ secrets.FLASK_SECRET_KEY }}
          echo "MONGO_URI = " + {{ secrets.MONGO_URI }}
          echo "LOGGING_LEVEL = 20"
          echo "FOOTBALL_DATA_KEY = " + {{ secrets.FOOTBALL_DATA_KEY }}
        write-mode: overwrite

    - name: Initialize Google Cloud SDK
      uses: zxyle/publish-gae-action@master
      with:
        service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.PROJECT_ID }}

    - name: Publish app to Google App Engine
      run: |
        gcloud auth activate-service-account ${{ secrets.SERVICE_ACCOUNT_EMAIL }} --key-file=client-secret.json
        gcloud config set project ${{ secrets.PROJECT_ID }}
        gcloud -q app deploy app.yaml --promote
